### ISSUE TITLE
Question: Should we be resolving data instead of entire responses?

### ISSUE THREAD

**Issue by lukewestby** [nraboy/ng-imgur#5]
The Imgur API returns a response wrapper with the interface

``` typescript
interface ImgurApiResponse<T> {
    status: number;
    success: boolean;
    data: T|ImgurApiError
}
```

Currently in `ng-imgur` responses are resolved as-is into the promise created by each method. Should we instead be resolving only the `data` member of the response?

**Comment by nraboy** [comment]
I thought about this as well, but was concerned there may one day be a scenario where we need more than just what resides in `data`.  This scenario may never come, but I wasn't sure.

I'm open to returning what is in `data` if you are :-)

**Comment by lukewestby** [comment]
My thinking is that, because the `status` parameter maps to the actual status code of the request and `success` essential maps to whether the status code was 200 or not, all of that information is pretty much encapsulated by the promise being resolved or rejected.

I'll submit a pull request sometime in the next few days. Thanks Nic!

**Comment by nraboy** [comment]
You're awesome dude!

Sorry, I've left the project hanging.  Been wrapped up with a personal item.  Hoping to get back into this and help you soon.

Thanks,
